---
##                       ._____.   .__
##  _____    ____   _____|__\_ |__ |  |   ____             ____ _____    ______
##  \__  \  /    \ /  ___/  || __ \|  | _/ __ \   ______  /    \\__  \  /  ___/
##   / __ \|   |  \\___ \|  || \_\ \  |_\  ___/  /_____/ |   |  \/ __ \_\___ \
##  (____  /___|  /____  >__||___  /____/\___  >         |___|  (____  /____  >
##       \/     \/     \/        \/          \/               \/     \/     \/
##     a n s i b l e - n a s      https://github.com/davestephens/ansible-nas

# Add your all.yml config overrides to this file. See group_vars/all.yml for all possible settings.

# Example options
ansible_nas_hostname: minimind
ansible_nas_timezone: Etc/UTC

# Global settings
docker_home: /mnt/data/docker

## Enable some applications
homepage_enabled: false

# Will be added to the docker group to give user command line access to docker
ansible_nas_user: schowell

# Your email and domain, used for Let's Encrypt SSL certs
ansible_nas_email: phonyfalcon@proton.me

###
### Aplications
###

# # Heimdall Dashboard
# heimdall_enabled: true
# heimdall_port_http: 10080
# # http://192.168.62.63:10800

# # Plex Server
# plex_enabled: true
# # http://192.168.62.63:32400/web/index.html

# Valheim Server
valheim_enabled: true
valheim_world: "ChineeseCheckers"
valheim_name: "ChineeseCheckers"
valheim_password: "cheese"
valheim_public: "1"  # test turning off this setting
valheim_auto_update: "0"
valheim_auto_backup: "0"
valheim_auto_update_pause_with_players: "1"
valheim_auto_update_schedule: "0 2 * * *"
valheim_auto_backup_pause_with_no_players: "1"
valheim_webhook_url: "https://discord.com/api/webhooks/1379629195398873188/Eh7gYA5RHXQ8RAHIJgG4YE-0iqJVc2jQG93M-EMySMDr0WALtkRefXarFWAbz2UTa42n"
valheim_webhook_include_public_ip: "1"
valheim_player_event_notifications: "1"
valheim_update_on_startup: "1"
# valheim_enable_crossplay: "0"
valheim_modifiers: "deathpentalty=casual"
valheim_set_key: "playerevents"
valheim_mods: ""  # come back to this
# valheim_scheduled_restart: "1"
# valheim_scheduled_restart_schedule: "0 3 * * *"

# Minecraft Server
minecraft_server_enabled: false

# # Minecraft Bedrock Server
# minecraft_bedrock_server_enabled: true
